#!/bin/sh
Adb() {
	cat << EOF
functions:
	AdbGetFocus
	AdbUninstall
EOF
}
AdbGetFocus() {
	echo "Doesn't work anymore."
	return 5
	F="$(adb shell dumpsys window windows | awk '/mCurrentFocus/ {print $3}')"
	echo "$F" 1>&2; echo "$F"
}
AdbUnistall() {
	adb shell pm uninstall -k --user 0 "$@"
}
