#!/bin/sh
Adb() {
	cat << EOF
functions:
	AdbGetFocus
	AdbUninstall
	AdbUninstallFocus
EOF
}
AdbGetFocus() {
	F="$(adb shell dumpsys window windows | awk -F'[/ {}]+' '/mObscuringWindow/{print $4}')"
	echo "$F" 1>&2; echo "$F"
}
AdbUninstall() {
	adb shell pm uninstall -k --user 0 "$@"
}
AdbUninstallFocus() {
	AdbUninstall "$(AdbGetFocus)"
}
