#!/bin/sh

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
cache=$cachedir/AutoUpdated
Invl=5
cday=$(date +%j)

UpdateCache() {
	echo "$cday" > "$cache"
	echo "Updating cache file ($cache)."
}

case $1 in
(-f)
	Updating=True
;;
(-u)
	UpdateCache
	echo "????"
	exit 0
;;
('')
	Updating=
;;
esac

sleep 30
{ sudo -n pacman -Sy &&
  sudo -n pacman -Fy
} 2>&1 | {
	echo "${0##*/}"
	head
	echo "${0##*/}"
} >&2 || exit $?

if [ -f "$cache" ]
then
	passed=$((cday - $(cat "$cache")))
	echo "Days passed since last auto-update: $passed."
	if [ "$passed" -ge "$Invl" ] || [ "$passed" -le "-$Invl" ]
	then
		Updating=True
	fi
else
	Updating=True
fi

if [ -n "$Updating" ]
then
	Updates=$(pacman -Qu | awk '{ printf("%-23s %s\n", $1, $NF) }' )
	UpsNum=$(echo "$Updates" | wc -l)

	notify-send -t 15000 "Time for Updates!!!
Pacman: $UpsNum updates available." "$Updates"

	st tmux new 'sudo pacman -Su && echo "---- ----"; $SHELL'
	pacman -Quq > /dev/null ||
		UpdateCache
fi
