#!/bin/ksh

# usage: FFMPEG_split [-recode] media_file times_file name_format

case $1 in
(-recode)
	Rec='-recode'
	shift
;;
(*)
	Rec=
;;
esac

F=$1
T=$2
Fmt=$3

lr=0
pt=
ct=

while read -u3 l
do
	[ -z ${l###*} ] && continue
	pt=$ct
	ct=$l
	[ -z "$pt" ] && continue
	lr=$((lr + 1))
	FFMPEG_cut $Rec "$F" "$pt" "$ct" "$(printf "$Fmt" "$lr")"
done 3< "$T"
