#!/bin/sh

set -f
IFS='
'
ls_size() {
	awk '/^[^d]/ && NR > 1 {
		printf("%s\t", $5)
		for (i = 9; i < NF; ++i)
			printf $i " "
		print $NF
	}'
}

if [ -z "$fs" ]
then
	du -hd1 .
	ls -Shla | ls_size
else
	dirs=
	files=
	for f in $fs
	do
		f=${f#$PWD/}
		[ -d "$f" ] && {
			dirs="$dirs$IFS$f"
			continue
		}
		files="$files$IFS$f"
	done
	[ -n "$dirs" ] &&
		du -hd0 $dirs
	[ -n "$files" ] &&
		ls -Shl $files | ls_size
fi | sort -hr
