#!/bin/ksh

Read() {
	printf '%s' "$1"
	shift
	read "$@"
}

lfselect() {
	lf -remote "send $id select '$1'"
}

Select() {
	t=${Matches[c]}
	lfselect "$t"
	[ ! -d "$t" ] && {
		t=${t%/*}
	}
	lfselect "$t"
}

Read 'Jump to pattern: ' Pattern

i=0
IFS='
'
for Matches[i] in $(unset IFS; LF_Pattern "$@" $Pattern)
do
	((++i))
done

if [ "$i" -eq 0 ]
then
	printf '\e[7;31;47m%s\e[0m' "Pattern not found"
	exit 1
elif [ "$i" -eq 1 ]
then
	lfselect "${Matches[0]}"
	echo 'Only one match found.'
	exit 0
fi

c=0
Select

while Read "Matches for '$Pattern': ($((c+1))/$i) [j/k]: " ans
do
	while [ ${#ans} -gt 0 ]
	do
		case "$ans" in
		(*([0-9])j*)
			n=${ans%%j*}; n=${n:-1}; ans=j${ans#*j}
			c=$(( (c+n) % i ))
		;;
		(*([0-9])k*)
			n=${ans%%k*}; n=${n:-1}; ans=k${ans#*k}
			c=$(( (c-n) % i ))
			[ $c -lt 0 ] && c=$((c+i))
		;;
		(s*)
			lfselect "${Matches[c]}"
			break 2
		;;
		(a*)
			lfselect "$f"
			break 2
		;;
		(q*)
			break 2
		;;
		esac

		ans=${ans#?}
	done
	Select
done
