#!/bin/sh

marksf=${XDG_DATA_HOME:-$HOME/.local/share}/lf/marks

[ "${#1}" = 1 ] || {
	echo "${0##*/}: arguments must be one character" >&2
	exit 100
}

{
	echo "$1:$PWD"
	sed "/^$1:/d" "$marksf"
} | sponge "$marksf"
