#!/bin/sh

[ -n "${1#?}" -o -z "$1" ] && {
	echo "${0##*/}: arguments must be one character" >&2
	exit 100
}

marksfile=${XDG_DATA_HOME:-$HOME/.local/share}/lf/marks
tmpf=$(mktemp)
{
	echo "$1:$PWD"
	sed "/^$1:/d" "$marksfile"
} > "$tmpf"
mv -f "$tmpf" "$marksfile"
