#!/bin/sh

set -f
IFS='
'
op=$1
dest=$2
dups=$3
shift 3

if [ -z "$dest" ] || [ -z "$op" ]
then
	echo "$0: Wrong arguments."
	exit 0
fi

for i in "$@"
do
	d=${i%/*}
	[ "X$dups" != Xy ] && [ "X$d" = "X$dest" ] &&
		continue
	i=${i##*/}

	[ ! -e "$dest/$i" ] && {
		$op "$d/$i" "$dest"
		continue
	}

	read p s <<- EOF
	$(printf '%s\n' "$i" | sed -E 's/(.*)\ \(([0-9]+)\)/\1\n\2/')
	EOF

	echo "$p $s"

	[ -z "$s" ] &&
		s=1 ||
		s=$((s + 1))

	newn="$dest/$p ($s)"

	while [ -e "$newn" ]
	do
		newn="$dest/$p ($((s += 1)))"
	done

	$op "$d/$i" "$newn"
done
