#!/bin/sh

IFS='
'

LF_Clear
printf -- '--- Files to be removed: ---\n\n%s\n\nDelete? [y/n]: ' "$fx" \
	| LF_Fihi

read ans
if [ "$ans" != y ]
then
	messg='Aborted'
elif rm -vfR $fx | LF_Log
then
	messg='DONE'
else
	messg='SOME ERROR OCCURED'
fi

printf "\n--- $messg ---\n"
