#!/bin/sh

IFS='
'

LF_Clear
printf -- '--- Files to be removed: ---\n\n%s\n\nDelete? [y/n]: ' "$*" \
	| LF_Fihi

read ans
if [ "$ans" != y ]
then
	messg='Aborted'
elif rm -vfR "$@" | LF_Log "$ULOG"
then
	messg='DONE'
else
	messg='SOME ERROR OCCURED'
fi

printf "\n--- $messg ---\n"
