#!/bin/sh

q() { exit 0; }
Print() {
	s=$(Player.sh playlist-info) || return $?
	clear
	printf "%s" "$s"
}
Read() {
	printf %s 'Waiting... : '
	read cmd
	eval "$cmd"
}
Main() {
	Print
	while sleep .85
	do
		Print || Read
	done
}

trap 'echo; Read; Main' INT

Main
