#!/bin/sh

IFS='
'

Print() {
	LF_Clear
	for f in $(find ~/.config/mpv/watch_later -type f)
	do
		( read i; i=${i#??}
		  if [ -e "$i" ]
		  then
		  	echo "${i##*/}"
		  else
		  	echo "$i"
		  fi
		) < "$f"
	done | sort -nk2 |
	while read n
	do
		echo "$n"
	done
}

trap 'exec "$0" "$@"' INT

Print
while read ans
do
	Print
	case $ans in
	(q*)
		break
	;;
	esac
done
