#!/bin/sh

q() { exit 0; }
Print() {
	s=$(Player.sh playlist-info) || return $?
	clear
	printf "%s\n" "$s"
}
Read() {
	printf %s 'Waiting... : '
	read cmd
	eval "$cmd"
}

trap 'echo; Read' INT

Print
while sleep .989
do
	Print || Read
done
