#!/bin/sh

IFS='
'
box='<>'
PrintWhat() {
	for f in $(find ~/.config/mpv/watch_later -type f)
	do
		(
			read i; i=${i#??}
			if [ -e "$i" ]
			then
				i=${i%.*}
				echo "${i##*/}"
			else
				echo "$i"
			fi
		) < "$f"
	done | sort -nk2 |
		while read n
		do
			echo "$n"
		done
}
Print() {
	w=$(PrintWhat)
	LF_Clear
	echo "$box"
	[ -n "$w" ] &&
		printf '%s\n' "$w"
	echo "$box"
}

while true
do
	Print
	read ans
	case $ans in
	(q*)
		break
	;;
	(r*)
		exec "$0" "$@"
	;;
	esac
done
