#!/bin/sh

Hili() {
	RE=$1
	sed "s\`\($RE\)\`$(printf "\033[01;3${C}m%s\033[0m" '\1')\`g"
}

case $1 in
(--c[0-9])
	C=${1#--c}
	shift
;;
(*)
	C=2
;;
esac

if [ $# -ge 2 ]
then
	"$@" | Hili "$2"
else
	Hili "$1"
fi
