#!/bin/sh

Hili() {
	sed "s\`\($1\)\`$(printf "\033[01;3${C}m%s\033[0m" '\1')\`g"
}

case $1 in
(--c[0-9])
	C=${1#--c}
	shift
;;
(*)
	C=2
;;
esac

if [ $# -ge 2 ]
then
	RE=$2
	[ -n "$2" ] && [ "X${2%%-*}" = X ] && RE=$3
	"$@" | Hili "$RE"
else
	Hili "$1"
fi
