#!/bin/sh

Title="shot_$(date +'%Y%m%d_%H%M%S')"
wflag=

Shoot() {
	local fname=$1
	mkdir -p "${fname%/*}"
	shotgun $shootOpts "$fname"
}
Notify() {
	notify-send -t 3000 "$@"
}

if [ "X$1" = X-w ]
then
	shift
	wflag=y
else
	wflag=n
fi
dest="${1:-$HOME/Screenshots}"

if [ "X$wflag" = Xy ]
then
	fname="$dest/${Title}w.png"
	id=$(xdotool getwindowfocus)
	shootOpts="-i $id"
	msg="Window-Screenshot saved"
else
	fname="$dest/$Title.png"
	shootOpts=
	msg="Screenshot saved"
fi

Shoot "$fname" &&
	Notify -i "$fname" "$msg" "$fname" ||
	Notify 'Screenshot failed'
