#!/bin/sh
notify-send -i
DEST="$HOME/Screenshots"
Title="shot_$(date +'%Y%m%d_%H%M%S')"

Notify() {
	dunstify -t 3000 -i "$1" "$2"
}

if [ "$#" -le 0 ]
then
	fname="$DEST/$Title.png"
	shotgun "$fname"
	Notify "$fname" "Screenshot saved."
	exit 0
fi

[ $1 != window ] && exit 1

id=$(xdotool getwindowfocus)
fname="$DEST/${Title}w.png"
shotgun -i $id "$fname";
Notify "$fname" "Window-Screenshot saved."
