#!/bin/sh

DEST="$HOME/Screenshots"
Title="shot_$(date +'%Y%m%d_%H%M%S')"

Notify() {
	notify-send -t 3000 -i "$1" "$2"
}

case $1 in
(-w)
	fname="$DEST/${Title}w.png"
	id=$(xdotool getwindowfocus)
	opts="-i $id"
	msg="Window-Screenshot saved."
;;
(*)
	fname="$DEST/$Title.png"
	opts=
	msg="Screenshot saved."
;;
esac

shotgun $opts "$fname"
Notify "$fname" "$msg"
