#!/bin/sh

Status=
Locker='xsidle.sh'
NewTime=${1:-10}
if [ -n "$2" ]
then
	NewBlank=no
else
	NewBlank=
fi

DefTime=$(xset q | awk '/timeout/ {print $2" "$4}')
[ "$(xset q | awk '/blanking/ {print $3}')" = no ] &&
	BlankStyle=no

Set() {
	xset s $NewTime
	xset s ${NewBlank}blank
	printf "|-SS-\tTimeout changed: $NewTime\t${NewBlank}blank\n"
	printf "(II)\t"
	killall -v -STOP "$Locker"
	Status=S
}
Reset() {
	[ "x$Status" = xR ] && return 0
	xset s $DefTime 
	xset s ${BlankStyle}blank
	printf "|-RR-\tTimeout reset: $DefTime\t${BlankStyle}blank\n"
	printf "(II)\t"
	killall -v -CONT "$Locker"
	printf -- "\n---------------------------------------------------\n"
	Status=R
}
Pause() {
	read ans
	[ -n "$ans" ] && [ -z "${ans##q*}" ] &&
		exit 0
}

trap 'exit 0' INT TERM
trap 'Reset' exit

while true
do
	Set; Pause
	Reset; Pause
done
