#!/bin/sh

IFS='
'

for f in $(find "$@" -type f)
do
	newname=$(printf '%s\n' "${f##*/}" | awk '
		BEGIN {
			n = split("I II III IV V VI VII VIII IX X XI", Out)
		} {
			for (w = 1; w <= NF; w++) {
				for (i in Out) {
					if (Out[i] "." == $w)
						$w = i"."
				}
			}
		print
		}'
	)

	newfname=${f%/*}/$newname

	[ "X$newfname" != "X$f" ] &&
		mv -vi "$f" "${f%/*}/$newname"
done

