#!/bin/sh

a=25
while [ $((a += 1)) -le 33 ]
do
	trap ':' $a
done
trap 'continue' 30

xdotool getactivewindow windowsize 1500 40 windowmove 240 170
while true
do
	echo -n "\n$(Player.sh status)\t\t\t\t\t\t\t\t"
	sleep .9735 & wait $!
done
