#!/bin/ksh

a=25
while [ $((a += 1)) -le 32 ]
do
	trap '' $a
done
trap ':' 30

xdotool getactivewindow windowsize 1260 31 windowmove 255 -3

b='    '
typeset -R"$((COLS - ${#b} +1))" S 2> /dev/null || b='\t\t\t\t\t\t\t\t'
while true
do
	S=$(Player.sh status)
	echo -n "\n$S$b"
	sleep .9735 & wait $!
done
