#!/bin/sh

case $(nmcli networking connectivity) in
(full)
	conn='o'
;;
(limited)
	conn='?'
;;
(none)
	conn='x'
;;
(*)
	conn='?x'
;;
esac

eth=
wcon=
type=$(nmcli connection show --active | awk 'NR > 1 {print $(NF-1)}')

expr "X$type" : 'X.*ethernet' > /dev/null 2>&1 &&
	eth=E
expr "X$type" : 'X.*wifi' > /dev/null 2>&1 &&
	wcon=W

wifi=
[ "$(nmcli radio wifi)" = enabled ] &&
	wifi=w

printf '%s' "$wcon$eth$conn$wifi"

exit
