#!/bin/sh

all=$(amixer -M get Master)
VOL=${all%\%] *}
VOL=${VOL##* \[}
mute=${all##* \[}
mute=${mute%]}

MicMute=$(amixer get Capture)
[ -z "${MicMute##*\[on]*}" ] &&
	mic=' '

suf=%
[ "$mute" != on ] &&
	suf=!

printf '%s' "$mic$VOL$suf"
