#!/bin/sh

set -o nounset

[ $# -lt 2 ] && {
	echo "${0##*/}: usage: ${0##*/} btn blkn" >&2
	exit 2
}

btn=$1
blkn=$2

clear1=0
clear2=9
plpause1=1
plpause2=3
plspeed=2
kblt=4
netw=5
mixer=6
battery=7
date=8

#echo "${0##*/} btn:$btn blkn:$blkn" >&2
case $blkn in
($clear1|$clear2)
	sign=
	[ $btn = 2 ] &&
		STATUS_toggle_clear
;;
($plpause1|$plpause2)
	sign=1
	case $btn in
	(3)
		Player.sh play-pause
	;;
	esac
;;
($plspeed)
	sign=1
	case $btn in
	(2)
		Player.sh speed 1.0
	;;
	(3)
		Player.sh play-pause
	;;
	(4)
		Player.sh speed+ 0.1
	;;
	(5)
		Player.sh speed- 0.1
	;;
	(*)
		sign=
	;;
	esac
;;
($kblt)
	sign=2
	case $btn in
	(1)
		xkblt -t0
	;;
	(3)
		xkblt -t1
	;;
	(4)
		xkblt -a1
	;;
	(5)
		xkblt -s1
	;;
	esac
;;
($netw)
	sign=3
;;
($mixer)
	sign=4
	args=
	sink=Master
	case $btn in
	(2)
		sink=Capture
		args=toggle
	;;
	(3)
		args=toggle
	;;
	(4)
		args=5%+
	;;
	(5)
		args=5%-
	;;
	(8)
		args=35%
	;;
	(9)
		args=75%
	;;
	esac
	[ -n "$args" ] &&
		amixer -Mq set $sink $args
;;
($battery)
	sign=5
;;
($date)
	sign=
	[ $btn = 3 ] &&
		gsimplecal
;;
esac

[ -n "$sign" ] &&
	kill -$((31 - sign)) $SBLOCKS_PID
true
