#!/bin/sh

# always print two '\1'
trap '[ $? != 0 ] && printf "\1\1"' exit

. Player_lib.sh

SetInfoVars "pause loop loopPl        Title\
	CurrTime Duration RemTime            Speed" \
	    "pause loop loop-playlist media-title\
	time-pos duration playtime-remaining speed"

p=?
case $pause in
(true)
	p=''
;;
(false)
	p=''
;;
esac

case $loopPl in
(inf)
	lp=P
;;
([2-9]*)
	lp=${loopPl}P
;;
esac

use_lf=y
case $loop in
(inf)
	lf=
	[ -n "$lp" ] &&
		lf=F
;;
([0-9]*)
	lf=$loop
;;
(*)
	use_lf=
;;
esac

pa=
[ -e "$pidf" ] &&
	pa=!

[ -n "$use_lf$lp" ] &&
	l=" ($lp$lf)"

SetTimeVars CurrTime "$CurrTime" Duration "$Duration" RemTime "$RemTime"

printf "%.100s [%s %s] (-%s) \1x%s\1 %s" \
       "$Title" "$CurrTime" "$Duration" \
       "$RemTime" "$Speed" "$p$l$pa"
