#!/bin/sh

set -o nounset

[ $# -lt 2 ] && {
	echo "${0##*/}: usage: ${0##*/} btn blkn" >&2
	exit 2
}

btn=$1
blkn=$2

#echo "${0##*/} btn:$btn blkn:$blkn" >&2
case $blkn in
(0|7)
	sign=
	[ $btn = 2 ] &&
		STATUS_toggle_clear
;;
(1)
	sign=1
	case $btn in
	(3)
		Player.sh play-pause
	;;
	esac
;;
(2)
	sign=2
	case $btn in
	(1)
		xkblt -t0
	;;
	(3)
		xkblt -t1
	;;
	(4)
		xkblt -a1
	;;
	(5)
		xkblt -s1
	;;
	esac
;;
(3)
	sign=3
;;
(4)
	sign=4
	args=
	sink=Master
	case $btn in
	(2)
		sink=Capture
		args=toggle
	;;
	(3)
		args=toggle
	;;
	(4)
		args=5%+
	;;
	(5)
		args=5%-
	;;
	(8)
		args=35%
	;;
	(9)
		args=75%
	;;
	esac
	[ -n "$args" ] &&
		amixer -Mq set $sink $args
;;
(5)
	sign=5
;;
(6)
	sign=
	[ "$btn" = 3 ] &&
		gsimplecal
;;
esac

[ -n "$sign" ] &&
	kill -$((31 - sign)) $SBLOCKS_PID
true
