#!/bin/ksh

tilde() { sed "s!'$HOME!'~!g"; }

DEST="$HOME/Documents/ConfigFiles"

set -A Targets ~/.{config/{gsimplecal,zathura,dunst,lf,mpv,init.sh},local/{bin,scripts},tmux.conf,{vim,xinit,input}rc,profile} ~/{Notes,TODO}.txt

Exclude=~/.config/mpv/watch_later\*

Update() {
	a="[[ \$1 = $Exclude ]]"
	eval "$a" && { echo "Skipping $1."; return 2; }

	local bsnm=${1##*/}
	if [ -f "$1" ] && [ "$1" -nt "$2/$bsnm" ]
	then
		cp -pv "$1" "$2"
		return 0
	elif [ ! -d "$1" ]
	then
		return 1
	fi

	mkdir -p "$2/$bsnm"

	find "$1" -maxdepth 1 |
	    while read -r f
	    do
		[[ $1 == $f ]] && continue
		Update "$f" "$2/$bsnm"
	    done
}

printf "\n%s\n" "Copying to $DEST:" | tilde

i=-1; M=${#Targets[@]}
while [ $((++i)) -lt $M ]
do
	t=${Targets[i]}
	Update "$t" "$DEST" | tilde
done

echo
