#!/bin/ksh

N='
'
IFS="	$N"
tilde() {
	sed "s!'$HOME!'~!g" "$@"
}

DEST="$HOME/Documents/ConfigFiles"

Targets=
for t in \
	~/.{tmux.conf,{xinit,input,keynav}rc,gdbinit,profile,init.sh} \
	~/.X{modmap,Compose} \
	~/.config/{vis,nvim,lf,mpv,gsimplecal,zathura,dunst} \
	~/.local/{bin,scripts} \
	~/Notes.txt
do
	Targets="$Targets$N$t"
done

Excludes="
	$HOME/.config/mpv/watch_later
	$HOME/.config/nvim/
	$HOME/.config/colors/
"
Includes="
	$HOME/.config/nvim/\(init\|colors/noclown\).vim$
	$HOME/.config/nvim/colors$
"

set -f

Update() {
	skip=n
	for e in $Excludes
	do
		expr "$1" : "$e" > /dev/null && {
			skip=y
			break
		}
	done
	if [ $skip = y ]
	then
		for i in $Includes
		do
			expr "$1" : "$i" > /dev/null && {
				skip=n
				break
			}
		done
	fi
	[ $skip = y ] && {
		echo "Skipped '$1'." >> "$tmpf"
		return 2
	}
	local bsnm=${1##*/}
	if [ -f "$1" ] && [ "$1" -nt "$2/$bsnm" ]
	then
		cp -pv "$1" "$2"
		return 0
	elif [ ! -d "$1" ]
	then
		return 1
	fi

	mkdir -p "$2/$bsnm"

	find "$1" -maxdepth 1 -mindepth 1 |
		while read -r f
		do
			Update "$f" "$2/$bsnm"
		done
}

printf '\n%s\n' "Copying to $DEST:" | tilde

tmpf=$(mktemp)
for t in $Targets
do
	Update "$t" "$DEST" | tilde
done

echo
tilde "$tmpf"
rm -f "$tmpf"
