#!/bin/sh

# Xorg settings
xset m 11/2 0
xset s 900 600
xset s noblank
xset r rate 250 25
xset -dpms

setxkbmap -layout us,gr -option grp:shift_caps_toggle \
          -option grp:alt_shift_toggle

if [ -z "${USER##*u*}" ]
then
	# Synaptic settings for touchpad
	#	TapButton1=1
	synclient \
		TapButton1=0\
		TapButton2=3\
		TapButton3=2\
		HorizTwoFingerScroll=on\
		VertTwoFingerScroll=on\
		MinSpeed=0.5\
		MaxSpeed=3\
		AccelFactor=0.2\
		ClickTime=50\
		VertScrollDelta=-115\
		HorizScrollDelta=-60\
		VertTwoFingerScroll=1\
		HorizTwoFingerScroll=1\
		PalmDetect=1
else
	xmodmap -e 'keycode 135 = Super_R'
fi

if [ "X$1" != 'X-a' ]
then
	echo "${0##*/}: ----- X keymaps loaded. -----"
	exit 0
fi

[ $(pgrep Xorg | wc -l) -gt 1 ] && {
	D=-1
	while [ "$((D += 1))" -le "${DISPLAY#:}" ]
	do
		DISPLAY=":$D" xset s off
	done
}

amixer -q set Capture nocap &
amixer -Mq set Master 40%

echo "${0##*/}: ----- X settings loaded. -----"
