#!/bin/sh

b0=${0##*/}
log() {
	printf '%s: %s\n' "$b0" "$*" >&2
}

Xstartlf=$HOME/.Xstart.local
xmodmapf=$HOME/.Xmodmap

# Xorg settings
xset m 11/2 0
xset s 900 600
xset s blank
xset r rate 250 25
xset -dpms

xsetroot -solid gray0

setxkbmap -layout us,gr -option grp:shift_caps_toggle

[ -f "$xmodmapf" ] &&
	xmodmap "$xmodmapf"

if [ -x "$Xstartlf" ]
then
	"$Xstartlf"
elif [ -f "$Xstartlf" ]
then
	. "$Xstartlf"
fi

command -v synclient > /dev/null 2>&1 && {
	# Synaptic settings for touchpad
	#	TapButton1=1
	synclient \
		TapButton1=1\
		TapButton2=3\
		TapButton3=2\
		HorizTwoFingerScroll=on\
		VertTwoFingerScroll=on\
		MinSpeed=0.5\
		MaxSpeed=3\
		AccelFactor=0.2\
		ClickTime=50\
		VertScrollDelta=-115\
		HorizScrollDelta=-60\
		VertTwoFingerScroll=1\
		HorizTwoFingerScroll=1\
		PalmDetect=1
}

log "----- X keymaps loaded. -----"
[ "X$1" != 'X-a' ] &&
	exit 0

if [ $(pgrep Xorg | wc -l) -gt 1 ]
then
	D=-1
	while [ "$((D += 1))" -le "${DISPLAY#:}" ]
	do
		DISPLAY=":$D" xset s off
	done
fi

if [ ! -e "${setF=${TMPDIR-/tmp}/settings.onboot}" ]
then
	touch "$setF"
	sleep 3
	amixer -q set Capture nocap
	amixer -Mq set Master 40%
fi

log "----- X settings loaded. -----"
